version: '3'
services:
  api:
    build:
      context: ../../
    ports:
      - "8080:8080"
    networks:
      default:
        ipv4_address: 192.168.57.10
  frontend:
    build: frontend
    ports:
      - "80:8888"
    networks:
      default:
        ipv4_address: 192.168.57.11
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.57.0/16
